# Fabric Properties
# check these on https://modmuss50.me/fabric.html or https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.19.2
# Mod Properties
mod_version=1.0-SNAPSHOT
maven_group=dev.kagian
archives_base_name=Session-login
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.150.0+26.1.2
